[project]
org-name = "wso2"
version = "0.8.21"
authors = ["WSO2"]
repository = "https://github.com/wso2-ballerina/module-sonarqube"
keywords = ["ballerina", "sonarqube","sonarqube6"]
license = "Apache-2.0"
